openapi: 3.0.0
info:
  title: Restaurants Service
  version: 1.0.0
paths:
  /internal/restaurants/{id}:
    get:
      summary: Get restaurant by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '404':
          description: Not found
servers:
  - url: http://localhost:3003
